# -*- coding: utf-8 -*-
"""
Created on Tue Nov  7 14:47:39 2017

@author: imendoer
This script analyses the pickled dataframe generated by get_data.py
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import os
#%%

'''
Loop over all files in the current folder with .p as name, extract the date
from the filename and reads the file as dataframe. The .p files are generated
by the get_data.py function and contain the same information as the excel
files.
'''

def main():


    # get all files in current folder
    files = os.listdir('./')

    # get all files which end with .p
    file = [f for f in files if f.endswith('_corrected.p')]

    for f in file:
        # extract the date of the experiment
        name = f.split('_')[0]

        # read in the pickled dataframe
        df_corrected = pd.read_pickle(f)

        mask = ((df_corrected.wavenumber >= 1000) &
                (df_corrected.wavenumber <= 1850))

        df_slice = df_corrected.loc[mask, :]

        # make figure and axis handle (this is my preferred style)
        fig, ax = plt.subplots(ncols=1, figsize=(8, 8))

        # plot the stuff
        df_slice.plot(x='wavenumber', ax=ax, cmap=plt.cm.viridis)\
                .legend(['First: dark blue', ])
        ax.set_title('{} Refold corrected'.format(name))
        ax.set_xlabel('Wavenumber')
        ax.set_ylabel('Absorbance')

        # save the figure
        plt.savefig('{}_corrected.png'.format(name), dpi=360)
        plt.close()


if __name__ == '__main__':
    main()