# -*- coding: utf-8 -*-
"""
Created on Tue Nov  7 14:47:39 2017

@author: imendoer
This script analyses the pickled dataframe generated by get_data.py
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import os
#%%

'''
Loop over all files in the current folder with .p as name, extract the date
from the filename and reads the file as dataframe. The .p files are generated
by the get_data.py function and contain the same information as the excel
files.
'''

def main():


    # get all files in current folder
    files = os.listdir('./')

    # get all files which end with .p
    file = [f for f in files if f.endswith('_raw.p')]
    # make figure and axis handle (this is my preferred style)
    fig, ax = plt.subplots(nrows=len(file), figsize=(8, 3*len(file)))
    fig.subplots_adjust(hspace=0.5)
    for i, f in enumerate(file):
        # extract the date of the experiment
        date = f.split('_')[0]
        name = f.split('_')[1]

        # read in the pickled dataframe
        df = pd.read_pickle(f)
        data = df.drop(['date', 'name'], axis=1).T


        mask = ((data.index >= 1000) &
                (data.index <= 1850))

        df_slice = data.loc[mask, :]



        # plot the stuff
        df_slice.plot(ax=ax[i], cmap=plt.cm.viridis)\
                .legend(['First: dark blue', ])

        ax[i].set_title('{} {}'.format(date, name))
        ax[i].set_xlabel('Wavenumber')
        ax[i].set_ylabel('Absorbance')

    # save the figure
    plt.savefig('spectra_all.png', dpi=190)
    plt.close()


if __name__ == '__main__':
    main()